server:
   port: 8761

spring:
  profiles: peer1
  application:
    name: eureka-server

eureka:
   instance:
       instance-id: peer1
       prefer-ip-address: true
   client:
       serviceUrl:
           defaultZone: http://z.z.z.z:8761/eureka/,http://y.y.y.y:8761/eureka/
