server:
   port: 8761

spring:
  profiles: peer2
  application:
    name: eureka-server

eureka:
   instance:
#       hostname: peer2
       prefer-ip-address: true
       instance-id: peer2
   client:
       serviceUrl:
#           defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
           defaultZone: http://x.x.x.x:8761/eureka/,http://z.z.z.z:8761/eureka/
