server:
   port: 8761

spring:
   profiles: peer3
   application:
       name: eureka-server
eureka:
   instance:
#       hostname: peer3
       prefer-ip-address: true
       instance-id: peer3
   client:
       serviceUrl:
#           defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
           defaultZone: http://x.x.x.x:8761/eureka/,http://y.y.y.y:8761/eureka/
