server:
   port: 8762

#spring:
#  profiles: peer2

eureka:
   instance:
#       hostname: peer2
       prefer-ip-address: true
   client:
       serviceUrl:
#           defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
           defaultZone: http://10.135.7.56:8761/eureka/,http://10.135.6.66:8763/eureka/
