server:
   port: 8763

#spring:
#  profiles: peer3

eureka:
   instance:
#       hostname: peer3
#       prefer-ip-address: true
#   client:
       serviceUrl:
#           defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
           defaultZone: http://10.135.7.56:8761/eureka/,http://10.135.7.58:8762/eureka/
