spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8791

# zuul网关
zuul:
  routes:
    api-a:
      path: /api-ribbon/**
      serviceId: ribbon-consumer
    api-b:
      path: /api-feign/**
      serviceId: feign-consumer