# 通用部分配置项
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  # 设置cluster的名字，配合turbine使用
  instance:
    metadata-map:
     cluster: ribbon

spring:
  application:
    name: ribbon-consumer
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 10.133.42.153:9092
  profiles:
    active: 8781


management:
  endpoints:
    web:
      exposure:
        include: "*,hystrix.stream"

---
server:
  port: 8781
spring:
  profiles: 8781

---
server:
  port: 8783
spring:
  profiles: 8783
