eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
#    instance:
#        lease-renewal-interval-in-seconds: 1
#        lease-expiration-duration-in-seconds: 2
server:
    port: 8762
spring:
    application:
        name: service-hello